### ISSUE TITLE
Add a syntax for overriding the underscore-prefix precluding doc generation.

### ISSUE THREAD

**Issue by willnationsdev** [Dragoncraft89/godotdoc#1]
>     # This function will not show up, because it is prefixed with an underscore
>     func _bar():
> 	    return 1337

If this does not generate things, then users will be unable to generate documentation about virtual methods that are intentionally prefixed with an underscore and are meant to be overridden by subsequent users. Here is a possible example of using an exclamation point in such a case:

    # base_item.gd
    extends Resource
    class_name BaseItem
    
    #! When using our API to trigger an item, the plugin will automatically call this method
    #! on the selected item.
    func _use() -> void:
        pass

**Comment by TheDuriel** [comment]
Not only virtual methods, but it would require massive refactoring of some projects. The underscore prefix has been advocated as a privacy indicator. "Don't call or use this." My studio is sitting on thousands of lines of code formatted this way.

**Comment by yvie-k** [comment]
After thinking about it for a bit I think there are two things that can be done:
* Add an option to turn off this behaviour
* Add hints for the tool to override this behaviour like \# [Show] or \# [Hide]

I'm just not sure what should be the default behaviour: Hide prefixed methods or show them?

**Comment by TheDuriel** [comment]
I'd say be verbose and allow people to change the behavior when needed.
